### ISSUE TITLE
pyLangevitour

### ISSUE THREAD

**Issue by Wytamma** [pfh/langevitour#7]
Hi @pfh! 

Thanks for developing langevitour it is an amazing package! Your talk yesterday inspired me to start using langevitour in my research. I primarily work in Python and so I developed a python interface for langevitour here -> [https://github.com/Wytamma/pyLangevitour](https://github.com/Wytamma/pyLangevitour). 

I would be very happy to contribute this code back to your repo if you'd like to keep all the interfaces in one place? I'd be happy to open a PR and merge the pyLangevitour with your repo. Either way I'll added you as a collaborator on the pyLangevitour repo so you can make changes if you like. Please let me know what you think.

Kind regards, 

Wytamma

**Comment by pfh** [comment]
Hi @Wytamma,

This is great! A PR would be very welcome.

A few notes:
* I have a concern about the groups and levels code. It seems if I specify levels, the order of levels could be scrambled. I think levels needs to be passed to as_factor and used to initialize the mapping.
* numpy.linalg.svd could be used instead of scipy, scipy is a fairly large dependency to have.
* To be consistent with elsewhere the class name should be "Langevitour" without a capital T.

**Comment by Wytamma** [comment]
Excellent! I'll prepare and submit the PR this week :D

Also, do you have a PYPI account? I can add you as an own of the [langevitour project](https://pypi.org/project/langevitour/) so you can upload python releases to PYPI.

**Comment by pfh** [comment]
Hi @Wytamma,

Thanks. My PyPI username is pfh

**Comment by pfh** [comment]
Pull request received and merged. New version uploaded to PyPI. 

Thank you very much for this! It's been many years since I released a Python package, so I would have been quite baffled by where to start with the currently popular tooling. Fantastic to see Langevitour running in Jupyter notebooks.

**Comment by Wytamma** [comment]
Really glad to contribute to an awesome open source project 😊 thanks for accepting my PR!
